source: .
markdown_ext: "md"

remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme

title: "Document Everything"
description: "Never enough time to document all the things I have learned"
